export const state = () => ({
  list: [
    {id: 1, title: 'ZOOTECNIA'},
    {id: 3, title: 'INGENIERIA FORESTAL'},
    {id: 8, title: 'TECONOLOGIA AGROINDUSTRIAL'},
    {id: 10, title: 'BIOLOGIA'},
    {id: 11, title: 'INGENIERIA DE SISTEMAS'},
    {id: 12, title: 'TECONOLOGIA JURIDICA'},
    {id: 13, title: 'TECONOLOGIA EN GESTION JUDICIAL Y CRIMINALISTICA'},
    {id: 14, title: 'QUIMICA'},
    {id: 16, title: 'LICENCIATURA EN MATEMATICAS'},
    {id: 17, title: 'BELLAS ARTES'},
    {id: 18, title: 'FISICA'},
    {id: 19, title: 'LIC EN EDUC BASICA CON ENFAS CIENCIAS NAT EDU AMBI'},
    {id: 20, title: 'LICENCIATURA EN INGLES'},
    {id: 21, title: 'INGENIERIA CIVIL'},
    {id: 22, title: 'INGENIERIA ELECTRICA'},
    {id: 23, title: 'INGENIERIA INDUSTRIAL'},
    {id: 24, title: 'INGENIERIA MECANICA'},
    {id: 26, title: 'INGENIERIA ELECTRONICA'},
    {id: 27, title: 'DISEÑO INDUSTRIAL'},
    {id: 28, title: 'LIC EN EDUC BASCIA ENFAS EN LENGUA CASTELLANA'},
    {id: 29, title: 'LICENCIATURA EN ESPAÑOL Y LITERATURA'},
    {id: 30, title: 'LICENCIATURA EN MUSICA'},
    {id: 31, title: 'INGENIERIA METALURGICA'},
    {id: 32, title: 'INGENIERIA DE PETROLEOS'},
    {id: 33, title: 'INGENIERIA QUIMICA'},
    {id: 34, title: 'GEOLOGIA'},
    {id: 37, title: 'FILOSOFIA'},
    {id: 39, title: 'MATEMATICAS'},
    {id: 41, title: 'TRABAJO SOCIAL'},
    {id: 44, title: 'HISTORIA'},
    {id: 45, title: 'ECONOMIA'},
    {id: 46, title: 'DERECHO'},
    {id: 51, title: 'ENFERMERIA'},
    {id: 52, title: 'MEDICINA'},
    {id: 56, title: 'FISIOTERAPIA'},
    {id: 57, title: 'NUTRICION Y DIETETICA'},
    {id: 58, title: 'MICROBIOLOGIA Y ANALISIS'},
    {id: 59, title: 'TURISMO'},
    {id: 60, title: 'HISTORIA Y ARCHIVISTICA'},
    {id: 61, title: 'ARTES PLASTICAS'},
    {id: 62, title: 'INGENIERIA DE PROCESOS DE REFINICACION Y PETROQUIMIC'},
    {id: 63, title: 'LIC.LENGUAS EXTRANJERAS CON ENFASIS EN INGLES'},
    {id: 64, title: 'LICENCIATURA EN LITERATURA Y LENGUA CASTELLANA'},
    {id: 68, title: 'LICENCIATURA EN EDUCACION BASICA PRIMARIA'},
    {id: 70, title: 'TECNOLOGIA EMPRESARIAL'},
    {id: 71, title: 'GESTION EMPRESARIAL'},
    {id: 82, title: 'TECNOLOGIA EN REGENCIA DE FARMACIA'},
    {id: 84, title: 'TECNOLOGIA AGROPECUARIA'},
    {id: 86, title: 'PRODUCCION AGROINDUSTRIAL'},
    {id: 87, title: 'TECNICO PROFESIONAL EN PRODUCCION AGROPECUARIA'},
    {id: 89, title: 'ADMINISTRACION AGROINDUSTRIAL'},
  ]
})

export const actions = {}

export const mutations = {}

